import '../scss/style.scss';
import { accordion } from './modules/accordion';
import { counter } from './modules/counter';
import { photoViewer } from './modules/photoViewer';
import { message } from './modules/message';
import { placeSelector } from './modules/place';
import { quize } from './modules/quize';
import { arr } from './modules/arr';
import { todo } from './modules/todo';
import { tabs } from './modules/tabs';

accordion();
counter();
photoViewer();
message();
placeSelector();
quize();
arr();
todo();
tabs();